# Generated by Django 3.0.3 on 2020-03-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Jadawl12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField()),
                ('ruang', models.IntegerField()),
                ('mapel', models.CharField(max_length=100)),
                ('jam_ke', models.CharField(max_length=100)),
            ],
        ),
    ]
