# Generated by Django 3.0.3 on 2020-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snesma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadawl12',
            name='kode_guru',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
