# Generated by Django 3.0.3 on 2020-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snesma', '0002_jadawl12_kode_guru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadawl12',
            name='hari',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='jadawl12',
            name='jam_ke',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jadawl12',
            name='kode_guru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jadawl12',
            name='mapel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jadawl12',
            unique_together={('hari', 'ruang', 'jam_ke')},
        ),
    ]
