# Generated by Django 3.0.3 on 2020-03-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snesma', '0005_jadawl3'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadawl12',
            name='kode_guru2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
